AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Gemfile'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 150

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: []
    '%i': '[]'
    '%I': '[]'
    '%w': '[]'
    '%W': '[]'
    '%r': '{}'
